### PR TITLE
Add a support for PHP 8.0 and upper

### PR DESCRIPTION
**Pull request by kudashevs**
Hello @iranianpep ,

I would like to propose adding the support for PHP 8.0 and upper versions. This PR contains the next changes:
- remove `composer.lock` (if you don't want to force users to use the specific versions of dependencies, you [don't commit it](https://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control))
- add the `WhitespaceTokenizer` class that replaces the NlpTools's equivalent. The original class doesn't work in new PHP versions because of some deprecations and the `nlp-tools` repo seems to be abandoned.
- add some changes to the tests, that make them work with new PHPUnit versions
- add composer `scripts` section with test commands
- add a `run-test.yml` Github Action (that replaces the travis one)
- change the code style to default one

This PR passes [all of the unit tests](https://github.com/kudashevs/keyword-extractor/actions/runs/12445732505).

### CODE REVIEW

**Comment by iranianpep** [comment]
@kudashevs, thanks for the PR. It seems the `styleci` check failed. Otherwise, it looks good to me

**Comment by kudashevs** [comment]
@iranianpep fixed.

**Review by iranianpep — APPROVED** [review]
LGTM! Thank you 🙏

**Comment by kudashevs** [comment]
@iranianpep Theoretically, if you follow the SemVer, this PR should lead to a new major release.
This happens because changing the minimum supported language version breaks the compatibility of the package. There is [a very interesting discussion](https://github.com/semver/semver/issues/148) on the topic.

**Comment by iranianpep** [comment]
Thanks. It's a fair point. I bumped the version to `[v1.1.0](https://github.com/iranianpep/keyword-extractor/releases/tag/v1.1.0)`

**Comment by kudashevs** [comment]
By major release I meant 2.0.0. But, it's up to the owner :)

**Comment by iranianpep** [comment]
It's backward compatible that's why I didn't bump it to v2.0.0 👍

**Pull request merged**
